### PR TITLE
48 - changed IP filtering to allow for IPv6 packets

### PR DESCRIPTION
**Pull request by curob**
Redo of pull request 50 but now with user information set.

### CODE REVIEW

**Comment by curob** [comment]
Curious, after this gets merged in, what is the delay before the python pip packages are updated? I use  ja3 in a test environment and would like to pull in the updates the "right way" as opposed to just pulling over the new source.

**Comment by curob** [comment]
@p-l- is there a timeline for this getting integrated and a new pip package distributed?

**Comment by p-l-** [comment]
@curob I do not handle this repository, sorry :)

**Comment by curob** [comment]
@p-l- oh, I had assumed since you approved the changes that you had the ability to merge this in (can you tell I am a gitbug novice? because I am...).

**Comment by p-l-** [comment]
@curob no worries! Anyone can review a PR, that was just to let you (and the repositories maintainers) that I have read your proposed patch and it looks good to me.

**Comment by curob** [comment]
4 weeks since pull request was approved... I ended up having to just pull the fixed code from this branch into my project instead of waiting for an "official" release. When (or if) this ever gets incorporated I will refactor accordingly.

**Pull request merged**
